### ISSUE TITLE
Discussion: use array of chars instead string as a alphabet

### ISSUE THREAD

**Issue by davydovanton** [peterhellberg/hashids.rb#19]
Hey!
Now we can use only string of chars as a alphabet for generating HashID. WDYT if gem will allow to use array of chars as a alphabet too?

Something like:
```ruby
alphabet = ['a1', 'b2']
hashids = Hashids.new("this is my salt", 0, alphabet)
hash = hashids.encode(1) # => "b2a1b2"
```

It will be helpful for generating hashes without any bad words or generating hashes with specific chars combinations. WDYT?

**Comment by peterhellberg** [comment]
I'm not sure that I see any benefit to this since you could just create the alphabet string from an array.

**Comment by davydovanton** [comment]
Thanks for quick reply 💯 

1. for example, I want to use sequence of chars like: `['a1', 'a2', 'b1', 'b2']`. In current realization it will be like: `'a1a2b1b2'` or just `'ab12'`. In this case, we'll have something like `aab2` instead `a1b1`
2. It should be optional (I forgot to add it, sorry)

**Comment by peterhellberg** [comment]
I will not consider anything that would break compatibility with the http://hashids.org/ specification.

**Comment by davydovanton** [comment]
okay, I got your point. Thanks, I'll close the issue 💗

**Comment by vkorobkov** [comment]
I would anticipate such a feature. There is a big problem when you generated public ids: how to remove or to skip bad words/phrases, including all the slang and the live nature of the language.

One of the best solutions, imo, which does not need curse words dictionaries/NLP analysis and which works well is to have a predefined sage alphabet like `A0`, `B5` and so on so any combination is never a bad word.

Don't see why alphabet can not be an array of strings instead of array of characters?
