### ISSUE TITLE
Hash collision

### ISSUE THREAD

**Issue by volkanunsal** [peterhellberg/hashids.rb#24]
I discovered a hash that decodes to 2 values in my codebase. My understanding from the documentation is there should be no collisions. Is this a bug?

```ruby
hex = "xaFG9d"
alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
h1 = Hashids.new("developments", 6, alphabet)
h1.decode(hex)
# => [29, 76161]
h2 = Hashids.new("tenants", 6, alphabet)
h2.decode(hex)
# => [42, 28612]
```

**Comment by peterhellberg** [comment]
I do not think there ever has been any guarantees that using different salts will not result in collisions.

The Hashids documentation states `“Allow custom alphabet as well as salt — so ids are unique only to you.”`

As well as `“There are no collisions because the method is based on integer to hex conversion. As long as you don't change constructor arguments midway, the generated output will stay unique to your salt.”`

**Comment by peterhellberg** [comment]
Note that Hashids shouldn’t be used for any security purposes:
https://carnage.github.io/2015/08/cryptanalysis-of-hashids

**Comment by volkanunsal** [comment]
Aha, I see. Thanks for the link.
